"""GBNF + JSON grammar artifacts for constrained decoding (issue #162).

Source is `vocabulary_document()` (`impl/lnpl/vocab.py`) — this module never
re-derives from `impl/lnpl/spec.py`/`lower.py`/`types.py` directly. Scope is
the closed-vocabulary tokens only (verbs, keywords, types, clauses, spec
`given`/`expect` forms) — no program-structure grammar, no inference-engine
integration. Never hand-edit `schemas/lnpl-grammar.gbnf` or
`schemas/lnpl-grammar.json`; both are generated by
`python scripts/gen_plugin_references.py` from the functions below.
"""

from lnpl.vocab import vocabulary_document

_BANNER = ("# generated — do not hand-edit. "
           "source: impl/lnpl/grammar.py:render_gbnf(). "
           "regenerate: python scripts/gen_plugin_references.py\n")

# (rule name, comment, vocab -> list[str] of terminal alternatives)
_RULES = (
    ("verb", None, lambda vocab: sorted(vocab["verbs"])),
    ("top_keyword", None, lambda vocab: list(vocab["keywords"]["top"])),
    ("clause_keyword", None, lambda vocab: list(vocab["keywords"]["clause"])),
    ("control_keyword", None,
     lambda vocab: list(vocab["keywords"]["control"])),
    ("semantic_type", None, lambda vocab: sorted(vocab["types"]["semantic"])),
    ("comparator", None, lambda vocab: list(vocab["keywords"]["comparators"])),
    ("arithmetic_op", None,
     lambda vocab: list(vocab["keywords"]["arithmetic_operators"])),
    ("logical_op", None,
     lambda vocab: list(vocab["keywords"]["logical_operators"])),
    ("policy_clause", None, lambda vocab: list(vocab["clauses"]["policy"])),
    ("security_clause", None,
     lambda vocab: list(vocab["clauses"]["security"])),
    ("performance_clause", None,
     lambda vocab: list(vocab["clauses"]["performance"])),
    ("spec_expect", None,
     lambda vocab: list(vocab["spec_expectations"]["expects"])),
    ("spec_given_form",
     "# spec_given_form enumerates the closed set of given-form TEMPLATES "
     "(patterns contain <field>-style placeholders), documenting which forms "
     "exist — it is not a decoding constraint for concrete given-clauses.",
     lambda vocab: [entry["pattern"]
                    for entry in vocab["spec_expectations"]["given_forms"]]),
)


def _gbnf_quote(token):
    escaped = token.replace("\\", "\\\\").replace('"', '\\"')
    return '"%s"' % escaped


def render_gbnf(vocab=None):
    """GBNF text: one rule per closed set, in `_RULES` order."""
    vocab = vocab or vocabulary_document()
    lines = [_BANNER]
    for name, comment, source in _RULES:
        if comment is not None:
            lines.append(comment + "\n")
        alternatives = " | ".join(_gbnf_quote(item) for item in source(vocab))
        lines.append("%s ::= %s\n" % (name, alternatives))
    return "".join(lines)


def grammar_json_document(vocab=None):
    """JSON manifest: the vocabulary document plus a `_generated` marker."""
    vocab = vocab or vocabulary_document()
    return {
        "_generated": {
            "by": "scripts/gen_plugin_references.py",
            "source": "impl/lnpl/grammar.py:grammar_json_document()",
            "hand_edit": False,
        },
        "vocabulary": vocab,
    }
