receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  file:
    path: /out/spans.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, file]
